packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@kirklin/logger': ^0.0.2
  '@kirklin/palette': ^0.1.1
  '@tanstack/query-persist-client-core': ^5.59.16
  '@tanstack/query-sync-storage-persister': ^5.59.16
  '@tanstack/vue-query': ^5.59.16
  '@tanstack/vue-table': ^8.20.5
  '@vicons/ionicons5': ^0.12.0
  '@vicons/tabler': ^0.12.0
  '@vue/shared': ^3.5.12
  '@vueuse/core': ^11.1.0
  '@vueuse/integrations': ^11.1.0
  '@faker-js/faker': ^9.1.0
  '@types/node': ^22.8.2
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vue/compiler-dom': ^3.5.12
  '@vue/test-utils': ^2.4.6
  '@types/lodash-es': ^4.17.12
  animate.css: ^4.1.1
  axios: ^1.7.7
  bignumber.js: ^9.1.2
  colord: ^2.9.3
  crypto-js: ^4.2.0
  dayjs: ^1.11.13
  destr: ^2.0.3
  detect-mobile: ^0.0.0
  echarts: ^5.5.1
  echarts-gl: ^2.0.9
  headless-highlighter: ^0.0.0
  iso-639-1: ^3.1.3
  lodash-es: ^4.17.21
  mockjs: ^1.1.0
  nprogress: ^0.2.0
  path-to-regexp: ^8.2.0
  pinia: ^2.2.4
  pinia-plugin-persistedstate: ^4.1.2
  pkg-types: ^1.2.1
  vite: ^5.4.10
  vue: ^3.5.12
  vue-draggable-plus: ^0.5.4
  vue-echarts: ^7.0.3
  vue-i18n: ^10.0.4
  vue-router: ^4.4.5
  naive-ui: ^2.40.1
  cross-env: ^7.0.3
  dotenv: ^16.4.5
  eslint: ^8.57.0
  jsdom: ^25.0.1
  nitropack: ^2.9.7
  pnpm: ^9.12.3
  prettier: ^3.2.5
  rollup-plugin-gzip: ^4.0.1
  rollup-plugin-visualizer: ^5.12.0
  turbo: ^2.2.3
  typescript: ^5.6.3
  unocss: ^0.63.6
  unocss-preset-chinese: ^0.3.3
  unocss-preset-ease: ^0.0.4
  unplugin-auto-import: ^0.18.3
  unplugin-vue-components: ^0.27.4
  vite-plugin-inspect: ^0.8.7
  vite-plugin-pwa: ^0.20.5
  vite-plugin-vue-devtools: ^7.5.4
  vitest: ^2.1.4
  vue-tsc: ^2.1.8 
